// import D2C from "@/assets/tema/basic/1.webp"

export const TEMA_TYPE = [
  { value: 'basic' as const, label: 'Basic' },
  { value: 'premium' as const, label: 'Premium' },
  { value: 'aqiqah' as const, label: 'Aqiqah' },
  { value: 'birthday' as const, label: 'Birthday' },
]

export const TEMA = [
  {
    name: "Adat Jawa",
    image: require("@/assets/tema/basic/1.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-jawa/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Jawa",
    image: require("@/assets/tema/basic/2.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-jawa/?to=Nama+Tamu",
  },
  {
    name: "Floral 02",
    image: require("@/assets/tema/basic/3.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-02/?to=Nama+Tamu",
  },
  {
    name: "Elegant 01",
    image: require("@/assets/tema/basic/4.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/elegant-01/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 01",
    image: require("@/assets/tema/basic/5.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-01/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 02",
    image: require("@/assets/tema/basic/6.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-02/?to=Nama+Tamu",
  },
  {
    name: "Floral 01",
    image: require("@/assets/tema/basic/7.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-01/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 03",
    image: require("@/assets/tema/basic/8.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-03/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 07",
    image: require("@/assets/tema/basic/9.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-07/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 08",
    image: require("@/assets/tema/basic/10.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-08/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 05",
    image: require("@/assets/tema/basic/11.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-05/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 04",
    image: require("@/assets/tema/basic/12.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-04/?to=Nama+Tamu",
  },
  {
    name: "Syar'i 02",
    image: require("@/assets/tema/basic/13.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/syari-02/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Minang",
    image: require("@/assets/tema/basic/14.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-minang/?to=Nama+Tamu",
  },
  {
    name: "Art 01",
    image: require("@/assets/tema/basic/15.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-01/?to=Nama+Tamu",
  },
  {
    name: "Garden 07",
    image: require("@/assets/tema/basic/16.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-07/?to=Nama+Tamu",
  },
  {
    name: "Floral 03",
    image: require("@/assets/tema/basic/17.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-03/?to=Nama+Tamu",
  },
  {
    name: "Syar'i 01",
    image: require("@/assets/tema/basic/18.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/syari-01/?to=Nama+Tamu",
  },
  {
    name: "Garden 01",
    image: require("@/assets/tema/basic/19.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-01/?to=Nama+Tamu",
  },
  {
    name: "Syar'i 03",
    image: require("@/assets/tema/basic/20.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/syari-03/?to=Nama+Tamu",
  },
  {
    name: "White Lily",
    image: require("@/assets/tema/basic/21.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/white-lily/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Lampung",
    image: require("@/assets/tema/basic/22.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-lampung/?to=Nama+Tamu",
  },
  {
    name: "Floral 12",
    image: require("@/assets/tema/basic/23.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-12/?to=Nama+Tamu",
  },
  {
    name: "Floral 05",
    image: require("@/assets/tema/basic/24.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-05/?to=Nama+Tamu",
  },
  {
    name: "Garden 02",
    image: require("@/assets/tema/basic/25.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-02/?to=Nama+Tamu",
  },
  {
    name: "Floral 13",
    image: require("@/assets/tema/basic/26.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-13/?to=Nama+Tamu",
  },
  {
    name: "Floral 14",
    image: require("@/assets/tema/basic/27.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-14/?to=Nama+Tamu",
  },
  {
    name: "Floral 18",
    image: require("@/assets/tema/basic/28.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-18/?to=Nama+Tamu",
  },
  {
    name: "Art 02",
    image: require("@/assets/tema/basic/29.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-02/?to=Nama+Tamu",
  },
  {
    name: "Adat Aceh",
    image: require("@/assets/tema/basic/30.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-aceh/?to=Nama+Tamu",
  },
  {
    name: "Adat Minang",
    image: require("@/assets/tema/basic/31.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-minang/?to=Nama+Tamu",
  },
  {
    name: "Floral 08",
    image: require("@/assets/tema/basic/32.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-08/?to=Nama+Tamu",
  },
  {
    name: "Adat Batak",
    image: require("@/assets/tema/basic/33.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-batak/?to=Nama+Tamu",
  },
  {
    name: "Elegant 02",
    image: require("@/assets/tema/basic/34.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/elegant-02/?to=Nama+Tamu",
  },
  {
    name: "Floral 06",
    image: require("@/assets/tema/basic/35.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-06/?to=Nama+Tamu",
  },
  {
    name: "Art 03",
    image: require("@/assets/tema/basic/36.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-03/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 06",
    image: require("@/assets/tema/basic/37.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-06/?to=Nama+Tamu",
  },
  {
    name: "Floral 04",
    image: require("@/assets/tema/basic/38.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-04/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Batak",
    image: require("@/assets/tema/basic/39.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-batak/?to=Nama+Tamu",
  },
  {
    name: "Floral 07",
    image: require("@/assets/tema/basic/40.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-07/?to=Nama+Tamu",
  },
  {
    name: "Garden 04",
    image: require("@/assets/tema/basic/41.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-04/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Toraja",
    image: require("@/assets/tema/basic/42.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-toraja/?to=Nama+Tamu",
  },
  {
    name: "Floral 20",
    image: require("@/assets/tema/basic/43.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-20/?to=Nama+Tamu",
  },
  {
    name: "Garden 03",
    image: require("@/assets/tema/basic/44.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-03/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Betawi",
    image: require("@/assets/tema/basic/45.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-betawi/?to=Nama+Tamu",
  },
  {
    name: "Floral 09",
    image: require("@/assets/tema/basic/46.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-09/?to=Nama+Tamu",
  },
  {
    name: "Garden 08",
    image: require("@/assets/tema/basic/47.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-08/?to=Nama+Tamu",
  },
  {
    name: "Art 04",
    image: require("@/assets/tema/basic/48.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-04/?to=Nama+Tamu",
  },
  {
    name: "Garden 05",
    image: require("@/assets/tema/basic/49.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-05/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Bali",
    image: require("@/assets/tema/basic/50.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-bali/?to=Nama+Tamu",
  },
  {
    name: "Floral 15",
    image: require("@/assets/tema/basic/51.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-15/?to=Nama+Tamu",
  },
  {
    name: "Floral 23",
    image: require("@/assets/tema/basic/52.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-23/?to=Nama+Tamu",
  },
  {
    name: "Art 05",
    image: require("@/assets/tema/basic/53.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-05/?to=Nama+Tamu",
  },
  {
    name: "Floral 22",
    image: require("@/assets/tema/basic/54.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-22/?to=Nama+Tamu",
  },
  {
    name: "Floral 21",
    image: require("@/assets/tema/basic/55.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-21/?to=Nama+Tamu",
  },
  {
    name: "Floral 10",
    image: require("@/assets/tema/basic/56.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-10/?to=Nama+Tamu",
  },
  {
    name: "Garden 06",
    image: require("@/assets/tema/basic/57.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-06/?to=Nama+Tamu",
  },
  {
    name: "Floral 11",
    image: require("@/assets/tema/basic/58.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-11/?to=Nama+Tamu",
  },
  {
    name: "Floral 17",
    image: require("@/assets/tema/basic/59.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-17/?to=Nama+Tamu",
  },
  {
    name: "Midnight At Garden",
    image: require("@/assets/tema/basic/60.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/midnight-at-garden/?to=Nama+Tamu",
  },
  {
    name: "Purple Lavender",
    image: require("@/assets/tema/basic/61.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/purple-lavender/?to=Nama+Tamu",
  },
  {
    name: "Floral 16",
    image: require("@/assets/tema/basic/62.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-16/?to=Nama+Tamu",
  },
  {
    name: "Floral 19",
    image: require("@/assets/tema/basic/63.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-19/?to=Nama+Tamu",
  },
  {
    name: "Java Heritage",
    image: require("@/assets/tema/premium/1.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/java-heritage/?to=Nama+Tamu",
  },
  {
    name: "Art Blue Java",
    image: require("@/assets/tema/premium/2.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/art-blue-java/?to=Nama+Tamu",
  },
  {
    name: "Bugis Heritage",
    image: require("@/assets/tema/premium/3.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/bugis-heritage/?to=Nama+Tamu",
  },
  {
    name: "Monochrome 06",
    image: require("@/assets/tema/premium/4.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/monochrome-06/?to=Nama+Tamu",
  },
  {
    name: "Minang Heritage",
    image: require("@/assets/tema/premium/5.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/minang-heritage/?to=Nama+Tamu",
  },
  {
    name: "Art Pink Castle",
    image: require("@/assets/tema/premium/6.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/art-pink-castle/?to=Nama+Tamu",
  },
  {
    name: "Art Royal Garden",
    image: require("@/assets/tema/premium/7.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/art-royal-garden/?to=Nama+Tamu",
  },
  {
    name: "Betawi Heritage",
    image: require("@/assets/tema/premium/8.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/betawi-heritage/?to=Nama+Tamu",
  },
  {
    name: "Monochrome 02",
    image: require("@/assets/tema/premium/9.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/monochrome-02/?to=Nama+Tamu",
  },
  {
    name: "Monochrome 01",
    image: require("@/assets/tema/premium/10.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/monochrome-01/?to=Nama+Tamu",
  },
  {
    name: "Monochrome 04",
    image: require("@/assets/tema/premium/11.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/monochrome-04/?to=Nama+Tamu",
  },
  {
    name: "Batak Heritage",
    image: require("@/assets/tema/premium/12.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/batak-heritage/?to=Nama+Tamu",
  },
  {
    name: "Fountain Garden",
    image: require("@/assets/tema/premium/13.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/fountain-garden/?to=Nama+Tamu",
  },
  {
    name: "Mansion Garden",
    image: require("@/assets/tema/premium/14.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/mansion-garden/?to=Nama+Tamu",
  },
  {
    name: "Moonlight Pavilion",
    image: require("@/assets/tema/premium/15.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/moonlight-pavilion/?to=Nama+Tamu",
  },
  {
    name: "Palembang Heritage",
    image: require("@/assets/tema/premium/16.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/palembang-heritage/?to=Nama+Tamu",
  },
  {
    name: "Celestial Temple",
    image: require("@/assets/tema/premium/17.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/celestial-temple/?to=Nama+Tamu",
  },
  {
    name: "Sunda Heritage",
    image: require("@/assets/tema/premium/18.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/sunda-heritage/?to=Nama+Tamu",
  },
  {
    name: "Melayu Heritage",
    image: require("@/assets/tema/premium/19.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/melayu-heritage/?to=Nama+Tamu",
  },
  {
    name: "Castle Garden",
    image: require("@/assets/tema/premium/20.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/castle-garden/?to=Nama+Tamu",
  },
  {
    name: "Art Minang",
    image: require("@/assets/tema/premium/21.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/art-minang/?to=Nama+Tamu",
  },
  {
    name: "Monochrome 05",
    image: require("@/assets/tema/premium/22.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/monochrome-05/?to=Nama+Tamu",
  },
  {
    name: "Glasshouse Garden",
    image: require("@/assets/tema/premium/23.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/glasshouse-garden/?to=Nama+Tamu",
  },
  {
    name: "Harbor Garden",
    image: require("@/assets/tema/premium/24.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/harbor-garden/?to=Nama+Tamu",
  },
  {
    name: "Starlit Citadel",
    image: require("@/assets/tema/premium/25.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/starlit-citadel/?to=Nama+Tamu",
  },
  {
    name: "Harmony Garden",
    image: require("@/assets/tema/premium/26.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/harmony-garden/?to=Nama+Tamu",
  },
  {
    name: "Art Chinese",
    image: require("@/assets/tema/premium/27.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/art-chinese/?to=Nama+Tamu",
  },
  {
    name: "Pavilion Garden",
    image: require("@/assets/tema/premium/28.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/pavilion-garden/?to=Nama+Tamu",
  },
  {
    name: "Moonlit Castle",
    image: require("@/assets/tema/premium/29.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/moonlit-castle/?to=Nama+Tamu",
  },
  {
    name: "Cottage Garden",
    image: require("@/assets/tema/premium/30.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/cottage-garden/?to=Nama+Tamu",
  },
  {
    name: "Lunar Falls",
    image: require("@/assets/tema/premium/31.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/lunar-falls/?to=Nama+Tamu",
  },
  {
    name: "Dainty Netherlands Tulip",
    image: require("@/assets/tema/premium/32.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/dainty-netherlands-tulip/?to=Nama+Tamu",
  },
  {
    name: "Monochrome 03",
    image: require("@/assets/tema/premium/33.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/monochrome-03/?to=Nama+Tamu",
  },
  {
    name: "Bali Heritage",
    image: require("@/assets/tema/premium/34.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/bali-heritage/?to=Nama+Tamu",
  },
  {
    name: "Dayak Heritage",
    image: require("@/assets/tema/premium/35.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/dayak-heritage/?to=Nama+Tamu",
  },
  {
    name: "Ethereal Falls",
    image: require("@/assets/tema/premium/36.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/ethereal-falls/?to=Nama+Tamu",
  },
  {
    name: "Dainty Serene Santorini",
    image: require("@/assets/tema/premium/37.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/dainty-serene-santorini/?to=Nama+Tamu",
  },
  {
    name: "Banjar Heritage",
    image: require("@/assets/tema/premium/38.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/banjar-heritage/?to=Nama+Tamu",
  },
  {
    name: "Safa Mosque",
    image: require("@/assets/tema/premium/39.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/safa-mosque/?to=Nama+Tamu",
  },
  {
    name: "Dainty Autumn Germany",
    image: require("@/assets/tema/premium/40.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/dainty-autumn-germany/?to=Nama+Tamu",
  },
  {
    name: "Nayyara Mosque",
    image: require("@/assets/tema/premium/41.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/nayyara-mosque/?to=Nama+Tamu",
  },
  {
    name: "Qamar Mosque",
    image: require("@/assets/tema/premium/42.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/qamar-mosque/?to=Nama+Tamu",
  },
  {
    name: "Qubbat Mosque",
    image: require("@/assets/tema/premium/43.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/qubbat-mosque/?to=Nama+Tamu",
  },
  {
    name: "Jabal Mosque",
    image: require("@/assets/tema/premium/44.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/jabal-mosque/?to=Nama+Tamu",
  },
  {
    name: "Dainty The Opera House Sydney",
    image: require("@/assets/tema/premium/45.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/dainty-the-opera-house-sydney/?to=Nama+Tamu",
  },
  {
    name: "Dainty Sunset In Singapore",
    image: require("@/assets/tema/premium/46.webp"),
    type: "premium",
    link: "https://invite.rangkaiweb.com/tema/dainty-sunset-in-singapore/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 09",
    image: require("@/assets/tema/aqiqah/1.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-09/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 06",
    image: require("@/assets/tema/aqiqah/2.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-06/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 07",
    image: require("@/assets/tema/aqiqah/3.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-07/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 08",
    image: require("@/assets/tema/aqiqah/4.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-08/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 01",
    image: require("@/assets/tema/aqiqah/5.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-01/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 11",
    image: require("@/assets/tema/aqiqah/6.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-11/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 03",
    image: require("@/assets/tema/aqiqah/7.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-03/?to=Nama+Tamu",
  },
  {
    name: "Tasmiyah 01",
    image: require("@/assets/tema/aqiqah/8.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/tasmiyah-01/?to=Nama+Tamu",
  },
  {
    name: "Tasmiyah 03",
    image: require("@/assets/tema/aqiqah/9.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/tasmiyah-03/?to=Nama+Tamu",
  },
  {
    name: "Tasmiyah 04",
    image: require("@/assets/tema/aqiqah/10.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/tasmiyah-04/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 02",
    image: require("@/assets/tema/aqiqah/11.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-02/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 04",
    image: require("@/assets/tema/aqiqah/12.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-04/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 05",
    image: require("@/assets/tema/aqiqah/13.jpg"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-05/?to=Nama+Tamu",
  },
  {
    name: "Aqiqah 10",
    image: require("@/assets/tema/aqiqah/14.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/aqiqah-10/?to=Nama+Tamu",
  },
  {
    name: "Tasmiyah 02",
    image: require("@/assets/tema/aqiqah/15.webp"),
    type: "aqiqah",
    link: "https://invite.rangkaiweb.com/tema/tasmiyah-02/?to=Nama+Tamu",
  },
  {
    name: "Little Dino",
    image: require("@/assets/tema/birthday/1.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-little-dino/?to=Nama+Tamu",
  },
  {
    name: "Butterfly Garden",
    image: require("@/assets/tema/birthday/2.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-butterfly-garden/?to=Nama+Tamu",
  },
  {
    name: "Ultah 10",
    image: require("@/assets/tema/birthday/3.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-10/?to=Nama+Tamu",
  },
  {
    name: "Astronot",
    image: require("@/assets/tema/birthday/4.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-astronot/?to=Nama+Tamu",
  },
  {
    name: "Ultah 03",
    image: require("@/assets/tema/birthday/5.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-03/?to=Nama+Tamu",
  },
  {
    name: "Ultah 01",
    image: require("@/assets/tema/birthday/6.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-01/?to=Nama+Tamu",
  },
  {
    name: "Ultah 11",
    image: require("@/assets/tema/birthday/7.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-11/?to=Nama+Tamu",
  },
  {
    name: "Happy 01",
    image: require("@/assets/tema/birthday/8.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/happy-01/?to=Nama+Tamu",
  },
  {
    name: "Ultah 02",
    image: require("@/assets/tema/birthday/9.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-02/?to=Nama+Tamu",
  },
  {
    name: "Happy 05",
    image: require("@/assets/tema/birthday/10.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/happy-05/?to=Nama+Tamu",
  },
  {
    name: "Ultah 12",
    image: require("@/assets/tema/birthday/11.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-12/?to=Nama+Tamu",
  },
  {
    name: "Cute Panda",
    image: require("@/assets/tema/birthday/12.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-cute-panda/?to=Nama+Tamu",
  },
  {
    name: "Happy 03",
    image: require("@/assets/tema/birthday/13.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/happy-03/?to=Nama+Tamu",
  },
  {
    name: "Honey Bee",
    image: require("@/assets/tema/birthday/14.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-honey-bee/?to=Nama+Tamu",
  },
  {
    name: "Pink Elephant",
    image: require("@/assets/tema/birthday/15.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-pink-elephant/?to=Nama+Tamu",
  },
  {
    name: "Ultah 04",
    image: require("@/assets/tema/birthday/16.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-04/?to=Nama+Tamu",
  },
  {
    name: "Ultah 06",
    image: require("@/assets/tema/birthday/17.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-06/?to=Nama+Tamu",
  },
  {
    name: "Ultah 08",
    image: require("@/assets/tema/birthday/18.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-08/?to=Nama+Tamu",
  },
  {
    name: "Dragon Adventure",
    image: require("@/assets/tema/birthday/19.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-dragon-adventure/?to=Nama+Tamu",
  },
  {
    name: "Happy 02",
    image: require("@/assets/tema/birthday/20.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/happy-02/?to=Nama+Tamu",
  },
  {
    name: "Happy 04",
    image: require("@/assets/tema/birthday/21.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/happy-04/?to=Nama+Tamu",
  },
  {
    name: "Happy Turtle",
    image: require("@/assets/tema/birthday/22.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-happy-turtle/?to=Nama+Tamu",
  },
  {
    name: "Little Baker",
    image: require("@/assets/tema/birthday/23.webp"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-little-baker/?to=Nama+Tamu",
  },
  {
    name: "Ultah 05",
    image: require("@/assets/tema/birthday/24.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-05/?to=Nama+Tamu",
  },
  {
    name: "Ultah 07",
    image: require("@/assets/tema/birthday/25.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-07/?to=Nama+Tamu",
  },
  {
    name: "Ultah 09",
    image: require("@/assets/tema/birthday/26.jpg"),
    type: "birthday",
    link: "https://invite.rangkaiweb.com/tema/ultah-09/?to=Nama+Tamu",
  },
];
