// import D2C from "@/assets/tema/basic/1.webp"

export const TEMA_TYPE = [
  "basic",
  "premium",
  "aqiqah",
  "birthday",
];

export const TEMA = [
  {
    name: "Adat Jawa",
    image: require("@/assets/tema/basic/1.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-jawa/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Jawa",
    image: require("@/assets/tema/basic/2.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-jawa/?to=Nama+Tamu",
  },
  {
    name: "Floral 02",
    image: require("@/assets/tema/basic/3.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-02/?to=Nama+Tamu",
  },
  {
    name: "Elegant 01",
    image: require("@/assets/tema/basic/4.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/elegant-01/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 01",
    image: require("@/assets/tema/basic/5.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-01/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 02",
    image: require("@/assets/tema/basic/6.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-02/?to=Nama+Tamu",
  },
  {
    name: "Floral 01",
    image: require("@/assets/tema/basic/7.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-01/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 03",
    image: require("@/assets/tema/basic/8.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-03/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 07",
    image: require("@/assets/tema/basic/9.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-07/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 08",
    image: require("@/assets/tema/basic/10.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-08/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 05",
    image: require("@/assets/tema/basic/11.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-05/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 04",
    image: require("@/assets/tema/basic/12.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-04/?to=Nama+Tamu",
  },
  {
    name: "Syar'i 02",
    image: require("@/assets/tema/basic/13.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/syari-02/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Minang",
    image: require("@/assets/tema/basic/14.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-minang/?to=Nama+Tamu",
  },
  {
    name: "Art 01",
    image: require("@/assets/tema/basic/15.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-01/?to=Nama+Tamu",
  },
  {
    name: "Garden 07",
    image: require("@/assets/tema/basic/16.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-07/?to=Nama+Tamu",
  },
  {
    name: "Floral 03",
    image: require("@/assets/tema/basic/17.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-03/?to=Nama+Tamu",
  },
  {
    name: "Syar'i 01",
    image: require("@/assets/tema/basic/18.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/syari-01/?to=Nama+Tamu",
  },
  {
    name: "Garden 01",
    image: require("@/assets/tema/basic/19.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-01/?to=Nama+Tamu",
  },
  {
    name: "Syar'i 03",
    image: require("@/assets/tema/basic/20.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/syari-03/?to=Nama+Tamu",
  },
  {
    name: "White Lily",
    image: require("@/assets/tema/basic/21.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/white-lily/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Lampung",
    image: require("@/assets/tema/basic/22.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-lampung/?to=Nama+Tamu",
  },
  {
    name: "Floral 12",
    image: require("@/assets/tema/basic/23.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-12/?to=Nama+Tamu",
  },
  {
    name: "Floral 05",
    image: require("@/assets/tema/basic/24.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-05/?to=Nama+Tamu",
  },
  {
    name: "Garden 02",
    image: require("@/assets/tema/basic/25.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-02/?to=Nama+Tamu",
  },
  {
    name: "Floral 13",
    image: require("@/assets/tema/basic/26.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-13/?to=Nama+Tamu",
  },
  {
    name: "Floral 14",
    image: require("@/assets/tema/basic/27.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-14/?to=Nama+Tamu",
  },
  {
    name: "Floral 18",
    image: require("@/assets/tema/basic/28.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-18/?to=Nama+Tamu",
  },
  {
    name: "Art 02",
    image: require("@/assets/tema/basic/29.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-02/?to=Nama+Tamu",
  },
  {
    name: "Adat Aceh",
    image: require("@/assets/tema/basic/30.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-aceh/?to=Nama+Tamu",
  },
  {
    name: "Adat Minang",
    image: require("@/assets/tema/basic/31.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-minang/?to=Nama+Tamu",
  },
  {
    name: "Floral 08",
    image: require("@/assets/tema/basic/32.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-08/?to=Nama+Tamu",
  },
  {
    name: "Adat Batak",
    image: require("@/assets/tema/basic/33.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-batak/?to=Nama+Tamu",
  },
  {
    name: "Elegant 02",
    image: require("@/assets/tema/basic/34.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/elegant-02/?to=Nama+Tamu",
  },
  {
    name: "Floral 06",
    image: require("@/assets/tema/basic/35.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-06/?to=Nama+Tamu",
  },
  {
    name: "Art 03",
    image: require("@/assets/tema/basic/36.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-03/?to=Nama+Tamu",
  },
  {
    name: "Minimalis 06",
    image: require("@/assets/tema/basic/37.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/minimalis-06/?to=Nama+Tamu",
  },
  {
    name: "Floral 04",
    image: require("@/assets/tema/basic/38.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-04/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Batak",
    image: require("@/assets/tema/basic/39.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-batak/?to=Nama+Tamu",
  },
  {
    name: "Floral 07",
    image: require("@/assets/tema/basic/40.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-07/?to=Nama+Tamu",
  },
  {
    name: "Garden 04",
    image: require("@/assets/tema/basic/41.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-04/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Toraja",
    image: require("@/assets/tema/basic/42.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-toraja/?to=Nama+Tamu",
  },
  {
    name: "Floral 20",
    image: require("@/assets/tema/basic/43.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-20/?to=Nama+Tamu",
  },
  {
    name: "Garden 03",
    image: require("@/assets/tema/basic/44.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-03/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Betawi",
    image: require("@/assets/tema/basic/45.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-betawi/?to=Nama+Tamu",
  },
  {
    name: "Floral 09",
    image: require("@/assets/tema/basic/46.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-09/?to=Nama+Tamu",
  },
  {
    name: "Garden 08",
    image: require("@/assets/tema/basic/47.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-08/?to=Nama+Tamu",
  },
  {
    name: "Art 04",
    image: require("@/assets/tema/basic/48.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-04/?to=Nama+Tamu",
  },
  {
    name: "Garden 05",
    image: require("@/assets/tema/basic/49.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-05/?to=Nama+Tamu",
  },
  {
    name: "Adat Art Bali",
    image: require("@/assets/tema/basic/50.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/adat-art-bali/?to=Nama+Tamu",
  },
  {
    name: "Floral 15",
    image: require("@/assets/tema/basic/51.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-15/?to=Nama+Tamu",
  },
  {
    name: "Floral 23",
    image: require("@/assets/tema/basic/52.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-23/?to=Nama+Tamu",
  },
  {
    name: "Art 05",
    image: require("@/assets/tema/basic/53.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/art-05/?to=Nama+Tamu",
  },
  {
    name: "Floral 22",
    image: require("@/assets/tema/basic/54.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-22/?to=Nama+Tamu",
  },
  {
    name: "Floral 21",
    image: require("@/assets/tema/basic/55.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-21/?to=Nama+Tamu",
  },
  {
    name: "Floral 10",
    image: require("@/assets/tema/basic/56.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-10/?to=Nama+Tamu",
  },
  {
    name: "Garden 06",
    image: require("@/assets/tema/basic/57.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/garden-06/?to=Nama+Tamu",
  },
  {
    name: "Floral 11",
    image: require("@/assets/tema/basic/58.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-11/?to=Nama+Tamu",
  },
  {
    name: "Floral 17",
    image: require("@/assets/tema/basic/59.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-17/?to=Nama+Tamu",
  },
  {
    name: "Midnight At Garden",
    image: require("@/assets/tema/basic/60.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/midnight-at-garden/?to=Nama+Tamu",
  },
  {
    name: "Purple Lavender",
    image: require("@/assets/tema/basic/61.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/purple-lavender/?to=Nama+Tamu",
  },
  {
    name: "Floral 16",
    image: require("@/assets/tema/basic/62.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-16/?to=Nama+Tamu",
  },
  {
    name: "Floral 19",
    image: require("@/assets/tema/basic/63.webp"),
    type: "basic",
    link: "https://invite.rangkaiweb.com/tema/floral-19/?to=Nama+Tamu",
  },
  {
    name: "Tema",
    image: "",
    type: "basic",
    link: "",
  },
  {
    name: "Tema",
    image: "",
    type: "basic",
    link: "",
  },
  {
    name: "Tema",
    image: "",
    type: "basic",
    link: "",
  },
  {
    name: "Tema",
    image: "",
    type: "basic",
    link: "",
  },
  {
    name: "Tema",
    image: "",
    type: "basic",
    link: "",
  },
];
